version: '2.2'

services:
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cache:/cache
